# Para docker image without any plugins

FROM maven:3.8-jdk-11-slim AS build

RUN mkdir -p /para
RUN curl -Ls https://github.com/Erudika/para/archive/master.tar.gz | tar -xz -C /para
RUN cd /para/para-master && mvn -q install -DskipTests=true -DskipITs=true && \
	cd /para/para-master/para-jar && mvn -q -Pbase clean package && mv target/para-[0-9]*.jar /para/

FROM adoptopenjdk/openjdk11:alpine-jre

ENV BOOT_SLEEP=0 \
    JAVA_OPTS="-Dloader.path=lib"

RUN mkdir -p /para/lib &&	mkdir -p /para/data

WORKDIR /para

VOLUME ["/para/data"]

COPY --from=build /para/para-*.jar /para/para.jar

EXPOSE 8080

CMD sleep $BOOT_SLEEP && \
    java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar para.jar
